// MCU Watch Order Guide — data
// Each item: saga, title, type ("movie" | "show"), year, month (1-12, null if TBA), desc (spoiler-free)

const DATA = {
  "Main MCU": [
    { title: "Iron Man", type: "movie", year: 2008, month: 5, desc: "A billionaire weapons manufacturer builds a high-tech suit of armor after a life-changing incident and sets out to right his past mistakes." },
    { title: "The Incredible Hulk", type: "movie", year: 2008, month: 6, desc: "A scientist on the run tries to control the rage-fueled creature within him while evading a relentless military pursuit." },
    { title: "Iron Man 2", type: "movie", year: 2010, month: 5, desc: "With his secret out, a hero faces new rivals, a personal health crisis, and a government eager to control his technology." },
    { title: "Thor", type: "movie", year: 2011, month: 5, desc: "A proud warrior prince is banished to Earth and must learn humility before he can reclaim his power and his home." },
    { title: "Captain America: The First Avenger", type: "movie", year: 2011, month: 7, desc: "A frail young man is transformed into a super-soldier to fight in World War II against a ruthless enemy organization." },
    { title: "The Avengers", type: "movie", year: 2012, month: 5, desc: "Earth's mightiest heroes are assembled for the first time to stop an other-worldly invasion threatening the planet." },
    { title: "Iron Man 3", type: "movie", year: 2013, month: 5, desc: "Haunted by past events, a hero must rely on his own resourcefulness after his world is torn apart by a mysterious terrorist." },
    { title: "Thor: The Dark World", type: "movie", year: 2013, month: 11, desc: "An ancient enemy threatens the Nine Realms, forcing an uneasy alliance to prevent universal destruction." },
    { title: "Captain America: The Winter Soldier", type: "movie", year: 2014, month: 4, desc: "A soldier uncovers a conspiracy within the very organization he serves, while facing a deadly assassin from his past." },
    { title: "Guardians of the Galaxy", type: "movie", year: 2014, month: 8, desc: "A group of misfit outlaws band together to stop a fanatic from acquiring a powerful artifact and endangering the galaxy." },
    { title: "Avengers: Age of Ultron", type: "movie", year: 2015, month: 5, desc: "A team's attempt to create a peacekeeping program backfires, unleashing an artificial intelligence bent on its own agenda." },
    { title: "Ant-Man", type: "movie", year: 2015, month: 7, desc: "A former thief gains a size-changing suit and must master it to pull off a high-stakes heist for the greater good." },
    { title: "Captain America: Civil War", type: "movie", year: 2016, month: 5, desc: "A rift among heroes over accountability and freedom forces old allies onto opposing sides of a devastating conflict." },
    { title: "Doctor Strange", type: "movie", year: 2016, month: 11, desc: "A brilliant but arrogant surgeon discovers a hidden world of mysticism after a tragic accident changes his path forever." },
    { title: "Guardians of the Galaxy Vol. 2", type: "movie", year: 2017, month: 5, desc: "The team faces new threats and old family ties as one member's true origins come to light." },
    { title: "Spider-Man: Homecoming", type: "movie", year: 2017, month: 7, desc: "A young hero balances high school life with the pressure to prove himself against a dangerous new threat in his city." },
    { title: "Thor: Ragnarok", type: "movie", year: 2017, month: 11, desc: "Stripped of his power and stranded far from home, a hero must find a way back to stop the destruction of his world." },
    { title: "Black Panther", type: "movie", year: 2018, month: 2, desc: "A new king returns home to a technologically advanced nation and must defend it from a challenger with a personal grudge." },
    { title: "Avengers: Infinity War", type: "movie", year: 2018, month: 4, desc: "Heroes from across the galaxy unite to stop a powerful being from acquiring all six Infinity Stones." },
    { title: "Ant-Man and the Wasp", type: "movie", year: 2018, month: 7, desc: "A hero teams up with a new partner on a rescue mission that plunges them into the mysterious quantum realm." },
    { title: "Captain Marvel", type: "movie", year: 2019, month: 3, desc: "A former Air Force pilot discovers extraordinary powers and gets caught up in an intergalactic conflict with a hidden past." },
    { title: "Avengers: Endgame", type: "movie", year: 2019, month: 4, desc: "The remaining heroes attempt one last mission to undo the devastation caused by their greatest defeat." },
    { title: "Spider-Man: Far From Home", type: "movie", year: 2019, month: 7, desc: "A young hero's school trip abroad is interrupted when he's recruited to face a new elemental threat." },
    { title: "WandaVision", type: "show", year: 2021, month: 1, desc: "Two former Avengers find their lives take a strange, sitcom-style turn in a seemingly perfect suburban town." },
    { title: "The Falcon and the Winter Soldier", type: "show", year: 2021, month: 3, desc: "Two allies team up on a global mission that tests their partnership and forces them to confront a legacy left behind." },
    { title: "Loki Season 1", type: "show", year: 2021, month: 6, desc: "A mischievous god finds himself recruited by a mysterious agency that polices time itself, with unexpected consequences." },
    { title: "Black Widow", type: "movie", year: 2021, month: 7, desc: "A former spy confronts a dangerous conspiracy tied to her past, and family ties she thought she'd left behind." },
    { title: "Shang-Chi and the Legend of the Ten Rings", type: "movie", year: 2021, month: 9, desc: "A man is drawn back into a hidden world of martial arts and confronts a legacy connected to his father's secret organization." },
    { title: "Eternals", type: "movie", year: 2021, month: 11, desc: "An ancient group of immortal beings reunite after centuries apart to face a threat to humanity's very existence." },
    { title: "Hawkeye", type: "show", year: 2021, month: 11, desc: "A veteran archer teams up with a determined young protégé while untangling a dangerous mess from his past." },
    { title: "Spider-Man: No Way Home", type: "movie", year: 2021, month: 12, desc: "A spell gone wrong tears open the multiverse, bringing new dangers and unexpected faces into a young hero's life." },
    { title: "Moon Knight", type: "show", year: 2022, month: 3, desc: "A man grappling with blackouts and lost memories discovers he shares his body and mind with another personality." },
    { title: "Doctor Strange in the Multiverse of Madness", type: "movie", year: 2022, month: 5, desc: "A sorcerer journeys through the dangers of the multiverse to protect a young woman with a mysterious ability." },
    { title: "Ms. Marvel", type: "show", year: 2022, month: 6, desc: "A New Jersey teenager and superhero fan discovers she has real powers of her own and must learn to use them." },
    { title: "Thor: Love and Thunder", type: "movie", year: 2022, month: 7, desc: "A hero's search for inner peace is interrupted by a galactic killer targeting gods, and a familiar face returns." },
    { title: "She-Hulk: Attorney at Law", type: "show", year: 2022, month: 8, desc: "A lawyer must balance her career and personal life after gaining powerful abilities of her own." },
    { title: "Werewolf by Night", type: "show", year: 2022, month: 10, desc: "A secret society of monster hunters gathers for a deadly competition following the death of their leader." },
    { title: "Black Panther: Wakanda Forever", type: "movie", year: 2022, month: 11, desc: "A nation mourns a great loss while facing a new underwater threat that puts the world at risk." },
    { title: "The Guardians of the Galaxy Holiday Special", type: "show", year: 2022, month: 11, desc: "The team attempts to give one of their own a perfect, if unconventional, holiday gift." },
    { title: "Ant-Man and the Wasp: Quantumania", type: "movie", year: 2023, month: 2, desc: "A family is pulled into the quantum realm and must contend with a powerful and dangerous new adversary." },
    { title: "Guardians of the Galaxy Vol. 3", type: "movie", year: 2023, month: 5, desc: "The team goes on one final mission to protect one of their own from a painful past that catches up with them." },
    { title: "Secret Invasion", type: "show", year: 2023, month: 6, desc: "A veteran agent uncovers a secret infiltration years in the making that threatens the security of the entire planet." },
    { title: "Loki Season 2", type: "show", year: 2023, month: 10, desc: "The fallout from a fractured timeline forces old allies to fight to save the organization that governs time." },
    { title: "The Marvels", type: "movie", year: 2023, month: 11, desc: "Three heroes with entangled powers must team up after they start unintentionally swapping places with each other." },
    { title: "Echo", type: "show", year: 2024, month: 1, desc: "A deaf woman with a troubled past returns to her hometown and must confront old ties to the criminal underworld." },
    { title: "Deadpool & Wolverine", type: "movie", year: 2024, month: 7, desc: "A wisecracking mercenary teams up with a reluctant, clawed anti-hero on a multiverse-spanning mission." },
    { title: "Agatha All Along", type: "show", year: 2024, month: 9, desc: "A powerful witch stripped of her magic sets off down a mysterious road with a group of unlikely companions." },
    { title: "Daredevil: Born Again Season 1", type: "show", year: 2025, month: 3, desc: "A lawyer by day and vigilante by night finds his double life colliding once again with an old enemy turned politician." },
    { title: "Captain America: Brave New World", type: "movie", year: 2025, month: 2, desc: "The new shield-bearer finds himself at the center of an international incident and a personal conspiracy." },
    { title: "Thunderbolts*", type: "movie", year: 2025, month: 5, desc: "A misfit group of antiheroes is thrown together on a dangerous mission with an uncertain agenda behind it." },
    { title: "Ironheart", type: "show", year: 2025, month: 6, desc: "A brilliant young inventor builds her own high-tech suit and gets pulled into a world of danger because of it." },
    { title: "The Fantastic Four: First Steps", type: "movie", year: 2025, month: 7, desc: "A family of explorers gains extraordinary abilities and must protect their world from a cosmic-scale threat." },
    { title: "Wonder Man", type: "show", year: 2026, month: null, desc: "An actor and stuntman gets drawn into a strange chapter of his life connected to a famous, powerful name." },
    { title: "Daredevil: Born Again Season 2", type: "show", year: 2026, month: null, desc: "TBA — release date not yet confirmed." },
    { title: "Vision Quest", type: "show", year: 2026, month: null, desc: "A synthetic being searches for identity and connection as he tries to rebuild a sense of self." },
    { title: "Spider-Man: Brand New Day", type: "movie", year: 2026, month: 7, desc: "A young hero's world shifts again as he navigates new relationships and a fresh set of threats." },
    { title: "Avengers: Doomsday", type: "movie", year: 2026, month: 12, desc: "A new, dangerous adversary forces heroes old and new to come together against overwhelming odds." },
    { title: "Avengers: Secret Wars", type: "movie", year: 2027, month: 12, desc: "TBA — plot details under wraps ahead of this two-part finale event." },
  ],
  "Netflix Saga": [
    { title: "Daredevil Season 1", type: "show", year: 2015, month: 4, desc: "A blind lawyer by day becomes a masked vigilante by night to clean up the crime-ridden streets of his neighborhood." },
    { title: "Jessica Jones Season 1", type: "show", year: 2015, month: 11, desc: "A hard-drinking private investigator with hidden powers is pulled back into a nightmare from her past." },
    { title: "Daredevil Season 2", type: "show", year: 2016, month: 3, desc: "A vigilante's methods are challenged by a lethal new player and a former ally with a very different code." },
    { title: "Luke Cage Season 1", type: "show", year: 2016, month: 9, desc: "A man with unbreakable skin and super strength tries to keep a low profile, but his neighborhood needs a protector." },
    { title: "Iron Fist Season 1", type: "show", year: 2017, month: 3, desc: "A man believed dead for years returns home with a mystical martial arts power and a company to reclaim." },
    { title: "The Defenders", type: "show", year: 2017, month: 8, desc: "Four street-level heroes reluctantly join forces to stop a secretive organization from destroying their city." },
    { title: "The Punisher Season 1", type: "show", year: 2017, month: 11, desc: "A former soldier wages a brutal one-man war against the criminals responsible for his family's death." },
    { title: "Jessica Jones Season 2", type: "show", year: 2018, month: 3, desc: "An investigator digs into the origins of her powers, unearthing secrets she isn't prepared for." },
    { title: "Luke Cage Season 2", type: "show", year: 2018, month: 6, desc: "A hero's grip on his neighborhood is tested by a ruthless new rival and painful family history." },
    { title: "Iron Fist Season 2", type: "show", year: 2018, month: 9, desc: "A martial artist faces a challenger for his title while trying to protect the people he cares about." },
    { title: "Daredevil Season 3", type: "show", year: 2018, month: 10, desc: "Physically and emotionally shattered, a vigilante must rebuild himself while his greatest enemy walks free." },
    { title: "The Punisher Season 2", type: "show", year: 2019, month: 1, desc: "A vigilante's attempt at a quiet life is upended when he's drawn into protecting a stranger from a new threat." },
    { title: "Jessica Jones Season 3", type: "show", year: 2019, month: 6, desc: "An investigator faces a killer whose ambitions push her toward a line she has always tried not to cross." },
  ],
  "MCU Animated": [
    { title: "What If...? Season 1", type: "show", year: 2021, month: 8, desc: "An all-powerful watcher explores an anthology of pivotal moments unfolding very differently than expected." },
    { title: "What If...? Season 2", type: "show", year: 2023, month: 12, desc: "The multiverse of possibilities continues with more familiar heroes facing unfamiliar, twisted circumstances." },
    { title: "What If...? Season 3", type: "show", year: 2024, month: 12, desc: "The anthology series wraps up its exploration of the multiverse with a run of standalone alternate stories." },
    { title: "Marvel Zombies", type: "show", year: 2024, month: 10, desc: "A group of survivors bands together against a horde of the infected in a dark, action-horror spinoff." },
    { title: "Eyes of Wakanda", type: "show", year: 2025, month: 8, desc: "An anthology following Wakandan warriors on covert, dangerous missions across different eras of history." },
  ],
  "Alternate Animated": [
    { title: "X-Men '97", type: "show", year: 2024, month: 3, desc: "A beloved animated team of mutants continues its story into new territory, honoring its 90s roots." },
    { title: "Your Friendly Neighborhood Spider-Man Season 1", type: "show", year: 2026, month: null, desc: "A fresh animated take on a young hero's earliest days learning what it means to wear the mask." },
  ],
  "Fox X-Men Universe": [
    { title: "X-Men", type: "movie", year: 2000, month: 7, desc: "A group of mutants with extraordinary abilities bands together to prevent an all-out war between mutants and humans." },
    { title: "X2: X-Men United", type: "movie", year: 2003, month: 5, desc: "A dangerous new enemy forces former rivals to work together to save both mutants and humankind." },
    { title: "X-Men: The Last Stand", type: "movie", year: 2006, month: 5, desc: "A cure for mutation sparks a divisive conflict, forcing a team to fight for its very survival." },
    { title: "X-Men Origins: Wolverine", type: "movie", year: 2009, month: 5, desc: "A clawed mutant's brutal past comes back to haunt him as he seeks revenge against those who wronged him." },
    { title: "X-Men: First Class", type: "movie", year: 2011, month: 6, desc: "Two young mutants forge an unlikely friendship before ideological differences set them on opposing paths." },
    { title: "The Wolverine", type: "movie", year: 2013, month: 7, desc: "A reluctant hero is drawn into a dangerous plot in Japan involving an old friend and a powerful enemy." },
    { title: "X-Men: Days of Future Past", type: "movie", year: 2014, month: 5, desc: "A mutant is sent back in time to prevent a chain of events that leads to a devastating future." },
    { title: "Deadpool", type: "movie", year: 2016, month: 2, desc: "A wisecracking mercenary gains accelerated healing powers and sets out on a personal quest for revenge." },
    { title: "X-Men: Apocalypse", type: "movie", year: 2016, month: 5, desc: "An ancient, immensely powerful mutant awakens and recruits followers to reshape the world in his image." },
    { title: "Logan", type: "movie", year: 2017, month: 3, desc: "An aging, weary hero cares for an ailing mentor while protecting a young girl with a familiar and dangerous gift." },
    { title: "Deadpool 2", type: "movie", year: 2018, month: 5, desc: "A mercenary assembles a ragtag team to protect a young mutant from a relentless time-traveling soldier." },
    { title: "Dark Phoenix", type: "movie", year: 2019, month: 6, desc: "A powerful mutant's abilities spiral out of control after a cosmic force awakens something within her." },
    { title: "The New Mutants", type: "movie", year: 2020, month: 8, desc: "A group of young mutants held in a secretive facility must confront their pasts and their own abilities." },
  ]
};